apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-config
  labels:
{{ include "service.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 500
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      containers:
      - name: {{ .Release.Name }}-init-db
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - '
          java -jar /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/liquibase-core-3.4.2.jar --driver=com.mysql.jdbc.Driver --classpath=/usr/local/tomcat/webapps/ROOT.war --changeLogFile=com/jingrui/jrap/db/liquibase.groovy --url=jdbc:mysql://{{ .Values.env.open.MYSQL_HOST }}:{{ .Values.env.open.MYSQL_PORT }}/{{ .Values.env.open.MYSQL_DB }}  --username={{ .Values.env.open.MYSQL_USER }} --password={{ .Values.env.open.MYSQL_PASS }} clearCheckSums ;java -Ddb.url=jdbc:mysql://{{ .Values.env.open.MYSQL_HOST }}:{{ .Values.env.open.MYSQL_PORT }}/{{ .Values.env.open.MYSQL_DB }} -Ddb.user={{ .Values.env.open.MYSQL_USER }} -Ddb.password={{ .Values.env.open.MYSQL_PASS }} -jar /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/liquibase-core-3.4.2.jar --driver=com.mysql.jdbc.Driver --classpath=/usr/local/tomcat/webapps/ROOT.war --changeLogFile=com/jingrui/jrap/db/liquibase.groovy --url=jdbc:mysql://{{ .Values.env.open.MYSQL_HOST }}:{{ .Values.env.open.MYSQL_PORT }}/{{ .Values.env.open.MYSQL_DB }}  --username={{ .Values.env.open.MYSQL_USER }} --password={{.Values.env.open.MYSQL_PASS }} update
          '
      restartPolicy: Never